name: Demo App

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

env:
  PATH_TO_APP: demo

jobs:
  lint:
    name: Lint Demo App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter analyze
        run: flutter analyze
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter format check
        run: dart format --set-exit-if-changed .
        working-directory: ${{ env.PATH_TO_APP }}

  test_and_build:
    name: "Web: Test Demo App & build on tags"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Setup Pages
        if: startsWith(github.ref, 'refs/tags/v') # Only run on version tags
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Install ChromeDriver
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
      - name: Verify ChromeDriver install
        run: chromedriver --version

      - name: Run integration tests (Web)
        run: |
          chromedriver --port=4444 &
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/demo_test.dart -d chrome --dart-define=CI=true
          # We have to check the output for failed tests matching the string "[E]"
          output=$(<output.log)
          if [[ "$output" =~ \[E\] ]]; then
          # You will see "All tests passed." in the logs even when tests failed.
          echo "All tests did not pass. Please check the logs for more information."
          exit 1
          fi
        working-directory: ${{ github.workspace }}

      - name: Build app for web
        # if: startsWith(github.ref, 'refs/tags/v') # Only build for deployment on tags
        run: flutter build web --base-href "${{ steps.pages.outputs.base_path }}/"
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v') # Only upload artifacts on tags
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PATH_TO_APP }}/build/web

  deploy:
    name: Deploy Demo App to GitHub Pages
    needs: test_and_build
    if: startsWith(github.ref, 'refs/tags/v') # Only deploy on version tags
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
