name: Pipeline Demo App

on:
  push:
    # Run on all pushes including tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # tag-pattern for deployment

env:
  PATH_TO_APP: demo

jobs:
  lint:
    name: Lint Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter analyze
        run: flutter analyze
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter format check
        run: dart format --set-exit-if-changed .
        working-directory: ${{ env.PATH_TO_APP }}

  build_and_test:
    name: Build & Test App
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Setup Pages
        if: startsWith(github.ref, 'refs/tags/v') # Only run on version tags
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Build app for web
        if: startsWith(github.ref, 'refs/tags/v') # Only build for deployment on tags
        run: flutter build web --base-href "${{ steps.pages.outputs.base_path }}/"
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v') # Only upload artifacts on tags
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PATH_TO_APP }}/build/web

  deploy:
    name: Deploy to GitHub Pages
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v') # Only deploy on version tags
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
