name: Demo App

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

env:
  PATH_TO_APP: demo

jobs:
  lint:
    name: Lint Demo App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter analyze
        run: flutter analyze
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter format check
        run: dart format --set-exit-if-changed .
        working-directory: ${{ env.PATH_TO_APP }}

  integration_test_ios:
    if: false
    name: "Integration Tests iOS"
    needs: lint
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 16"
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}
      - run: flutter test integration_test
        working-directory: ${{ env.PATH_TO_APP }}

  # Skip for now as there are problems setting the working directory for the emulator action (doesn't support it)
  integration_test_android:
    if: false
    name: "Integration Tests Android"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - run: echo $ANDROID_HOME
      - run: sdkmanager --install "build-tools;30.0.3"
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}
      - name: Run integration tests (Android)
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: (cd ${{ env.PATH_TO_APP }}; flutter test demo/integration_test/demo_test.dart)
          api: 31
          cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -cores 2 -memory 3072 -no-window
          tag: google_apis
          abi: x86_64

  integration_test_web:
    name: "Integration Tests Web"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Install ChromeDriver
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
      - name: Verify ChromeDriver install
        run: chromedriver --version

      - name: Run integration tests (Web)
        run: |
          chromedriver --port=4444 &
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/demo_test.dart -d web-server --dart-define=CI=true | tee output.log
          # We have to check the output for failed tests matching the string "[E]"
          output=$(<output.log)
          if [[ "$output" =~ \[E\] ]]; then
          # You will see "All tests passed." in the logs even when tests failed.
          echo "All tests did not pass. Please check the logs for more information."
          exit 1
          fi
        working-directory: ${{ env.PATH_TO_APP }}

  build_web:
    name: "Build Web"
    needs: integration_test_web
    # if#: startsWith(github.ref, 'refs/tags/v') #  Only deploy on version tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Build app for web
        run: flutter build web --base-href "${{ steps.pages.outputs.base_path }}/"
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PATH_TO_APP }}/build/web

  deploy:
    name: Deploy Demo App to GitHub Pages
    needs: build_web
    # if#: startsWith(github.ref, 'refs/tags/v') # Only deploy on version tags
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
