name: Flutter Json Forms Package

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

env:
  PATH_TO_APP: .

jobs:
  lint:
    name: Lint Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter analyze
        run: flutter analyze
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run flutter format check
        run: dart format --set-exit-if-changed .
        working-directory: ${{ env.PATH_TO_APP }}

  test:
    name: Test Package
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: "3.32.8"
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.PATH_TO_APP }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ env.PATH_TO_APP }}

  # Publish to pub.dev only on tag pushes after successful tests
  publish:
    name: Publish Package to pub.dev
    needs: [lint, test] # Only run after both lint and test jobs succeed
    if: startsWith(github.ref, 'refs/tags/v') # Only run on version tags
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    # with:
    #   working-directory: .
